### ISSUE TITLE
Sync values from cloud after Setting something.

### ISSUE THREAD

**Issue by pos-ei-don** [mampfes/ha_freeair_connect#3]
After changing any settings, the Freeair-Device updates all values in the cloud.
It would be nice if this integration syncs the updated values from the cloud, ablut 20seconds after it
changed something (speed or mode)

**Comment by mampfes** [comment]
Hi, I don't own any such device myself, therefore I can't test issues.

The only way (that I know) to get new values from the cloud is to poll it. This will be done by the integration every 10 minutes. So you should see the after after max. 10 minutes. Isn't that working properly?
Do you see faster updates in the browser based view?
I don't want to decrease the polling interval (by default) because their very!!! poor implementation must cause a huge load on the server for every poll - and I don't want to overload their servers if many instances of this integration poll data too often.

**Comment by pos-ei-don** [comment]
Hi!
Interesting, and Thank you for creating this integration while not using it yourself ...
I know about the poor implementation. the Device itself is bad aswell.
It does not connect to internet when getting 2 DNS IPs from DNS, ....

As I have several Devices, I don't need the 10 Minutes-Poll. But I don't mind!

Would it be possible to just add a "refresh" option, which i can manually start via an automation?

**Comment by mampfes** [comment]
> Would it be possible to just add a "refresh" option, which i can manually start via an automation?

Good idea. I think I can add this.

**Comment by pos-ei-don** [comment]
Thank you a lot! Will test it after my holiday...
