### ISSUE TITLE
Integration doesn't connect anymore

### ISSUE THREAD

**Issue by steffenrapp** [mampfes/ha_freeair_connect#6]
For me the integration doesn't work anymore. Or others also affected? Maybe blumartin changed something?

I get following error:
fetch failed for SN xxxxx: 404 Client Error: Not Found for url: https://www.freeair-connect.de/login.php

**Comment by eldi0s** [comment]
Same here.Am 06.03.2024 um 11:16 schrieb steffenrapp ***@***.***>:﻿
For me the integration doesn't work anymore. Or others also affected? Maybe blumartin changed something?
I get following error:
fetch failed for SN xxxxx: 404 Client Error: Not Found for url: https://www.freeair-connect.de/login.php

**Comment by sirius599** [comment]
Same error (fetch failed for SN xxxxx: 404 Client Error: Not Found for url: https://www.freeair-connect.de/login.php) after migrating HA to a new server.

**Comment by mampfes** [comment]
blumartin changed their website...

**Comment by novag** [comment]
There already is one. You  can enable it using the local freeAir Connect software. The API was implemented for use with the bluHome Connect controller [1], but at a first glance it looks like it should be possible to communicate with it without the controller. I haven't found time to take a closer look yet. A positive note: since the latest firmware, there are no annoying confirmation tones when the local API is used.

[1] https://blumartin.de/bluhome-connect/

**Comment by mampfes** [comment]
fixed in release 1.3.0
